name: Run Functions Weekly

on:
  schedule:
    - cron: '39 23 * * SAT' #Bitcoin
    - cron: '51 10 * * SAT' #Kaspa
    - cron: '08 11 * * TUE' #Kaspa

jobs:
  run-kaspa-buy:
    runs-on: ubuntu-latest
    if: github.event.schedule.cron == '51 10 * * SAT' || github.event.schedule.cron == '08 11 * * TUE'


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run kaspa_buy function
        run: |
          python buy_kaspa.py

      - name: Commit and push the updated CSV
        run: |
          CURRENT_DATE=$(date +'%Y-%m-%d')
          git config --global user.name "github-actions"
          git config --global user.email "50283360+revanyo@users.noreply.github.com"
          git add kaspa_buys.csv
          git commit -m "Update kaspa_buys.csv after running on $CURRENT_DATE"
          git push

  run-bitcoin-buy:
    runs-on: ubuntu-latest
    if: github.event.schedule.cron == '39 23 * * SAT'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run bitcoin_buy function
        run: |
          python buy_bitcoin.py 

      - name: Commit and push the updated CSV
        run: |
          CURRENT_DATE=$(date +'%Y-%m-%d')
          git config --global user.name "github-actions"
          git config --global user.email "50283360+revanyo@users.noreply.github.com"
          git add bitcoin_buys.csv
          git commit -m "Update bitcoin_buys.csv after running on $CURRENT_DATE"
          git push